### ISSUE TITLE
DOGE coin sent to DOGE token contract address

### ISSUE THREAD

**Issue by alexbtc89** [binance-chain/canonical-upgradeable-bep20#8]
GM dear contract owner. Unfortunately, I've sent DOGE tokens to DOGE token contract address, but I did not find the token return function in the smart contract there. I'm writing to you here because you are the only person who can help me. Here is TXID: https://bscscan.com/tx/0xc37023c85c69fce73d3e49e57d800a46ae124cd7c8ce571f7edd39f83f8e6a9c
My wallet address is: 0x12c604e03B9d89B8e5f6B1c65a35752E6c791B64
Amount of DOGE: 71037 DOGE
Can you help me get the tokens back to my wallet? If not, who can I contact if at all possible? I would be very grateful for any help

**Comment by isaacyuno** [comment]
You could try to contact Binance for BNB Pioneer Burn Program https://www.binance.com/en/support/announcement/binance-introduces-the-bnb-pioneer-burn-program-adjusts-bnb-token-burn-mechanics-7bcf4da5671d44a0a5118c2277773bb4

**Comment by alexbtc89** [comment]
Thank you so much bruh! It really works
